### ISSUE TITLE
Error: Failed to find request token in session

### ISSUE THREAD

**Issue by seungha-kim** [seungha-kim/7blocks#2]
```
Error: Failed to find request token in session
    at SessionStore.get (/home/ubuntu/7blocks-api/node_modules/passport-oauth1/l
ib/requesttoken/session.js:13:44)
    at Strategy.OAuthStrategy.authenticate (/home/ubuntu/7blocks-api/node_module
s/passport-oauth1/lib/strategy.js:214:33)
    at attempt (/home/ubuntu/7blocks-api/node_modules/passport/lib/middleware/au
thenticate.js:348:16)
    at authenticate (/home/ubuntu/7blocks-api/node_modules/passport/lib/middleware/authenticate.js:349:7)
    at Layer.handle [as handle_request] (/home/ubuntu/7blocks-api/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ubuntu/7blocks-api/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/ubuntu/7blocks-api/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/ubuntu/7blocks-api/node_modules/express/lib/router/layer.js:95:5)
    at /home/ubuntu/7blocks-api/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/ubuntu/7blocks-api/node_modules/express/lib/router/index.js:335:12)
    at next (/home/ubuntu/7blocks-api/node_modules/express/lib/router/index.js:275:10)
    at logger (/home/ubuntu/7blocks-api/node_modules/morgan/index.js:144:5)
    at Layer.handle [as handle_request] (/home/ubuntu/7blocks-api/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/ubuntu/7blocks-api/node_modules/express/lib/router/index.js:317:13)
    at /home/ubuntu/7blocks-api/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/ubuntu/7blocks-api/node_modules/express/lib/router/index.js:335:12)
```

**Comment by seungha-kim** [comment]
https://github.com/expressjs/session/issues/281#issuecomment-191327863
